### ISSUE TITLE
Messy commit history

### ISSUE THREAD

**Issue by the-blank-x** [TeamSpeedo/Speedo#1]
The commit history on this repository are very messy and I can't tell what changes are being done unless I _look at every single commit_.
Here are links on some git discipline:
- https://drewdevault.com/2019/02/25/Using-git-with-discipline.html
- https://chris.beams.io/posts/git-commit/

If needed I can teach you how to use git on the command line (even on Termux, I'm doing this because the commit history makes me want to jump off a hospital).

**Comment by ForbiddenLinkers** [comment]
No need for it
